module.exports = {

    itemNames: [
        "Aegis",
        "Arming Sword",
        "Bardiche",
        "Battle Axe",
        "Buckler",
        "Castillon Dagger",
        "Cinder",
        "Crossbow",
        "Crystal Ball",
        "Crystal Sword",
        "Double Axe",
        "Drum",
        "Elven Bow of Truth",
        "Falchion",
        "Famine",
        "Felling Axe",
        "Flanged Mace",
        "Flute",
        "Fulgor",
        "Halberd",
        "Hand Crossbow",
        "Hatchet",
        "Heater Shield",
        "Horsemans Axe",
        "Kris Dagger",
        "Kuma's Claw",
        "Kuma's Fang",
        "Life after Death",
        "Longbow",
        "Longsword",
        "Lute",
        "Lyre",
        "Magic Staff",
        "Morning Star",
        "Nipalan",
        "Pavise",
        "Pestilence",
        "Pulverizing Prayer",
        "Quarterstaff",
        "Rapier",
        "Recurve Bow",
        "Rondel Dagger",
        "Round Shield",
        "Short Sword",
        "Spear",
        "Spellbook",
        "Stiletto Dagger",
        "Survival Bow",
        "Viking Sword",
        "Viola",
        "War Maul",
        "Windlass Crossbow",
        "Zweihander",
        "Armet",
        "Barbuta Helmet",
        "Barbuta Helmet (Ruby Silver)",
        "Chapel De Fer",
        "Chapel De Fer (Cobalt)",
        "Chaperon",
        "Feathered Hat",
        "Forest Hood",
        "Gjermundbu",
        "Hood (Cobalt)",
        "Hood (Ruby Silver)",
        "Hounskull",
        "Kettle Hat",
        "Leather Bonnet",
        "Leather Cap",
        "Leather Cap (Ruby Silver)",
        "Occultist Hood",
        "Ranger Hood",
        "Rogue Cowl",
        "Shadow Hood",
        "Shadow Mask",
        "Straw Hat",
        "Viking Helmet",
        "Viking Helmet (Cobalt)",
        "Visored Barbuta Helmet",
        "Wizard Hat",
        "Wizard Hat (Cobalt)",
        "Adventurer Tunic",
        "Dark Plate Armor",
        "Doublet",
        "Fine Cuirass",
        "Frock",
        "Marauder Outfit",
        "Mystic Vestments",
        "Northern Full Tunic",
        "Occultist Robe",
        "Occultist Tunic",
        "Oracle Robe",
        "Padded Tunic",
        "Regal Gambeson",
        "Templar Armor",
        "Troubadour Outfit",
        "Wanderer Attire",
        "Warden Outfit",
        "Frock (Cobalt)",
        "Regal Gambeson (Cobalt)",
        "Templar Armor (Cobalt)",
        "Doublet (Ruby Silver)",
        "Fine Cuirass (Ruby Silver)",
        "Mystic Vestments (Ruby Silver)",
        "Bardic Pants",
        "Cloth Pants",
        "Heavy Leather Leggings",
        "Leather Chausses",
        "Leather Leggings",
        "Loose Trousers",
        "Padded Leggings",
        "Plate Pants",
        "Plate Pants (Cobalt)",
        "Trousers (Cobalt)",
        "Leather Leggings (Ruby Silver)",
        "Plate Pants (Ruby Silver)",
        "Heavy Gauntlet",
        "Leather Gloves",
        "Rawhide Gloves",
        "Reinforced Gloves",
        "Riveted Gloves",
        "Heavy Gauntlet (Cobalt)",
        "Leather Gloves (Cobalt)",
        "Heavy Gauntlet (Ruby Silver)",
        "Rawhide Gloves (Ruby Silver)",
        "Adventurer Boots",
        "Heavy Boots",
        "Laced Turnshoe",
        "Lightfoot Boots",
        "Occultist Boots",
        "Old Shoes",
        "Plate Boots",
        "Rugged Boots",
        "Wizard Shoes",
        "Adventurer Boots (Ruby Silver)",
        "Plate Boots (Ruby Silver)",
        "Lightfoot Boots (Cobalt)",
        "Plate Boots (Cobalt)",
        "Adventurers Cloak",
        "Radiant Cloak",
        "Splendid Cloak",
        "Tattered Cloak",
        "Rat Pendant",
        "Necklace of Peace",
        "Ox Pendant",
        "Badger Pendant",
        "Fox Pendant",
        "Ring of Survival",
        "Ring of Courage",
        "Ring of Resolve",
        "Ring of Quickness",
        "Healing Potion",
        "Potion of Protection",
        "Invisibility Potion",
        "Clarity Potion",
        "Potion of Luck",
        "Bandage",
        "Ale",
        "Surgical Kit",
        "Troll's Blood",
        "Lantern",
        "Lockpick",
        "Oil Lantern",
        "Golden Key",
        "Skull Key",
        "Campfire Kit",
        "Pickaxe",
        "Hunting Trap",
        "Throwing Knife",
        "Francisca Axe",
        "Explosion Bottle",
        "Cobalt Ore",
        "Cobalt Ingot",
        "Cobalt Powder",
        "Rubysilver Ore",
        "Rubysilver Ingot",
        "Rubysilver Powder",
        "Gold",

    ],

    //see above TODO
    itemRarity: ['Uncommon', 'Rare', 'Epic', 'Legendary', 'Unique'],

    itemProperties: [
        "Action Speed",
        "Additional Magical Damage",
        "Additional Physical Damage",
        "Agility",
        "All Attributes",
        "Armor Penetration",
        "Armor Rating",
        "Buff Duration Bonus",
        "Debuff Duration Bonus",
        "Headshot Damage Reduction",
        "Item Equip Speed",
        "Knowledge",
        "Magic Penetration",
        "Magic Resistance",
        "Magic Damage Reduction",
        "Magical Healing",
        "Magical Interaction Speed",
        "Magical Power",
        "Max Health",
        "Movement Speed Bonus",
        "Physical Damage Bonus",
        "Physical Damage Reduction",
        "Physical Healing",
        "Physical Power",
        "Projectile Reduction",
        "Regular Interaction Speed",
        "Resourcefulness",
        "Spell Capacity Bonus",
        "Spell Casting Speed",
        "Strength",
        "True Magical Damage",
        "True Physical Damage",
        "Weapon Damage",
        "Will",
    ],


}
